version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    networks:
      monitoring:
        aliases:
          - prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/config:/etc/prometheus:ro
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      monitoring:
        aliases:
          - grafana
    volumes:
      - ./grafana/dashboards:/etc/grafana/dashboards
      - grafana_data:/var/lib/grafana
      # - ./grafana/config/grafana.ini:/etc/grafana/grafana.ini
    environment:
      - GF_SECURITY_ADMIN_USER=david
      - GF_SECURITY_ADMIN_PASSWORD=david
      - GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION=false
    depends_on:
      - prometheus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 20

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      monitoring:
        aliases:
          - mon_exporter

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    networks:
      monitoring:
        aliases:
          - nginx
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/log/error.log:/var/log/nginx/error.log:rw
      - ./nginx/html:/usr/share/nginx/html:ro
    depends_on:
      grafana:
        condition: service_healthy

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:
  nginx_data:
