version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    # networks:
    #   monitoring:
    #     aliases:
    #       - prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/config:/etc/prometheus:ro
      - prometheus_data:/prometheus

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"
    # networks:
    #   monitoring:
    #     aliases:
    #       - mon_exporter

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager/config:/etc/alertmanager:ro
    # networks:
    #   monitoring:
    #     aliases:
    #       - mon_alert_man

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    # networks:
    #   monitoring:
    #     aliases:
    #       - prometheus
    volumes:
      - ./grafana/dashboards:/etc/grafana/dashboards
      - grafana_data:/var/lib/grafana

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:

  # loki:
  #   image: grafana/loki
  #   container_name: loki
  #   ports:
  #     - "3100:3100"
  #   # volumes:
  #   #   - ./loki/config/local-config.yaml:/etc/loki/local-config.yaml:ro

  # promtail:
  #   image: grafana/promtail
  #   container_name: promtail
  #   ports:
  #     - "9080:9080"
  #   volumes:
  #     - ./promtail/config/config.yml:/etc/promtail/config.yml
  #     # - /var/log:/var/log     ###### for mac #####
  #     - ./btc_app:/btc_app
  #     - ./nginx/log/error.log:/nginx/log/error.log

  # nginx:
  #   image: nginx
  #   container_name: nginx
  #   ports:
  #     - 80:80
  #   volumes:
  #     - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./nginx/log/error.log:/var/log/error.log:rw
  #     - ./nginx/html:/usr/share/nginx/html:ro

  # btc_app:
  #   build: ./btc_app
  #   container_name: btc_app
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./btc_app/btc_val.log:/app/btc_val.log
