version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    networks:
      monitoring:
        aliases:
          - prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/config:/etc/prometheus:ro
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      monitoring:
        aliases:
          - prometheus
    volumes:
      - ./grafana/dashboards:/etc/grafana/dashboards
      - grafana_data:/var/lib/grafana

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      monitoring:
        aliases:
          - mon_exporter

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:
